### ISSUE TITLE
CAN loopback frames

### ISSUE THREAD

**Issue by chemicstry** [samcrow/canadensis#11]
The library works great, however, I would like to use time synchronisation over canbus. The time synchronisation master requires loopback frames to know the precise transmission timestamp of its messages, but they don't seem to be implemented in canadensis. I would gladly make a PR, but I'm not sure what would be the best way to approach this.

The simlest solution without modifying canadensis internals would be to loopback everything as regular received messages and then check if source id matches current node id in `TransferHandler::handle_message`. But I'm not sure if this is the best approach, because it could cause weird bugs in other handlers if source id is not checked. It would also act weird in case of a node id conflict.

Another solution would be to add loopback flag to frames (maybe in `Transfer` and also in `canadensis_can::Frame`) and then have an additional `TransferHandler::handle_loopback(&mut self, 
node: &mut N, 
transfer: &Transfer)` method. This is similar to how [pycyphal](https://github.com/OpenCyphal/pycyphal/blob/1c4539390016eafb87b8377259b425883f19ee2e/pycyphal/transport/can/media/_frame.py#L66) does. This way loopback frames can be separated and don't interfere with regular frames.

Any thoughts?

**Comment by samcrow** [comment]
Adding a loopback flag sounds like a good idea.

The only problem I can think of is that some CAN controllers (bxCAN, MCP2515, maybe others) have loopback mode as a global switch and can't loopback specific frames only. The best solution might be documentation saying that some drivers may ignore the loopback flag.

Out of curiosity, what CAN controller are you using that can do loopback for specific frames?

**Comment by chemicstry** [comment]
I'm using bxCAN and it supports loopback only in debug mode (RX is disconnected). However, I'm aiming for a similar implementation as in the old [`libuavcan`](https://github.com/OpenCyphal-Garage/platform_specific_components/blob/legacy-v0/stm32/libuavcan/driver/src/uc_stm32_can.cpp#L684), where loopback is implemented in software and TX timestamp is captured in TX mailbox empty interrupt. This is not ideal, but if critical sections in software are short, you can get microsecond precision time synchronisation.

**Comment by pavel-kirienko** [comment]
It is reasonable to enable loopback in the driver for all frames and then silently drop all loopback frames except those few that were requested by the application to be reported back. It was implemented this way in the [original libuavcan driver for SocketCAN](https://github.com/OpenCyphal-Garage/platform_specific_components/blob/7c2f4ec48f5a0c274755ee1b383cb815f8f2b88f/linux/libuavcan/include/uavcan_linux/socketcan.hpp#L324), for example.

**Comment by samcrow** [comment]
Now that I understand the idea of using the interrupt to get a timestamp and do software loopback, this makes more sense. The driver part (canadensis_bxcan or similar) might be slightly challenging, but the rest of the changes seem simple.
