### ISSUE TITLE
UDP and Serial moving to big-endian for header_crc

### ISSUE THREAD

**Issue by maksimdrachov** [samcrow/canadensis#22]
See [forum](https://forum.opencyphal.org/t/cyphal-udp-architectural-issues-caused-by-the-dependency-between-the-nodes-ip-address-and-its-identity/1765/67)

In pycyphal, the following PR will fix this:

- Serial: https://github.com/OpenCyphal/pycyphal/pull/283

- UDPhttps://github.com/OpenCyphal/pycyphal/pull/284

**Comment by samcrow** [comment]
I updated the UDP and serial header format with recent commits on the master branch. I'm now just waiting for #21 before publishing releases.
