### ISSUE TITLE
canadensis_data_types refuses to build under no_std

### ISSUE THREAD

**Issue by ggoraa** [samcrow/canadensis#29]
https://github.com/starkat99/half-rs/issues/99

**Comment by samcrow** [comment]
Half 2.0.0 made the std feature enabled by default. I didn't notice that until later. [I fixed the problem](https://github.com/samcrow/canadensis/commit/9004e2ef0ea701ab5a4c1e0216512f0ecb75cdac), but didn't immediately release a new version.

I've now released canadensis_data_types 0.3.1 and patch releases for a few other packages, which should fix the problem.
